### ISSUE TITLE
Option to search a specific folder?

### ISSUE THREAD

**Issue by joefiorini** [neoclide/coc-lists#58]
VSCode's file search allows you to specify patterns of "files to include". Then it will only search files matching those patterns. `grep`, `ag` & `rg` all accept a path to search in. What do you think  about adding an option to `grep` like `-include` that takes a specific path (or pattern if it's supported by the tool) to include and passes them on to the underlying tool's `PATH` option?

**Comment by chemzqm** [comment]
There is `-folder` support, check help.

**Comment by joefiorini** [comment]
@chemzqm I did check help, a number of times, and I tried a couple different ways to pass a specific folder and none of them worked. I even looked at the [source code implementation of `-folder`](https://github.com/neoclide/coc-lists/blob/master/src/grep.ts#L149). My interpretation from doing all that is that `-folder` searches from the workspace root. That is different than what I am talking about here. I mean to pass a specific folder to `grep` so I could implement, for example, a shortcut to search in the folder of the file in the current buffer. Did I miss something that says `coc-list grep` supports this?

**Comment by chemzqm** [comment]
You should be able to pass path as last argument with rg, I've fixed it.

**Comment by joefiorini** [comment]
Wow, thanks for addressing so quickly! Will try it out later.

**Comment by joefiorini** [comment]
I'm finally getting around to playing with this fix and noticing that it still doesn't seem to work. For example, if I run:

```
CocList grep packages/some-package
```

I would expect, based on what you said, that it would limit the search to the `packages/some-package` folder. Instead, the list is prepopulated with results for `packages/some-package`. The problem, I suspect, is because `grep`, `ag` & `rg` expect the path to be the last positional param, but since the search pattern comes before it I can't prepopulate the command with the path. It seems like having a way to write a custom command that can inject the input (ie. replace %I with the input if it exists) would allow for this. Is there some other way to do this that I'm missing?
